<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4">
                <div class="well">
                    <span class="fa fa-lock fa-2x"> Login</span> 
                    <br><br>
                    <?php if ($this->error): ?>
                        <h4 class="text-danger"><b><span class="fa fa-warning"></span> Usuário ou senha inválidos</b></h4>
                        <hr />
                    <?php endif; ?>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('busao-admin-auth'));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formRow($form->get('email')) . "<br>";
                    echo $this->formRow($form->get('password')) . "<br>" . "<br>";
                    echo $this->formSubmit($form->get('submit')) . "<br>";
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->


<!-- jQuery 2.0.2 -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../js/bootstrap.min.js" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="../js/AdminLTE/app.js" type="text/javascript"></script>
<!-- AdminLTE for demo purposes -->
<script src="../js/AdminLTE/demo.js" type="text/javascript"></script>        
<!-- Bootstrap WYSIHTML5 -->
<script src="../jsplugins//bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
<!-- iCheck -->
<script src="../jsplugins//iCheck/icheck.min.js" type="text/javascript"></script>
<!-- Page script -->