<div class="content">

    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <div class="well">
                <span class="fa fa-lock fa-2x"> Login</span> 
                <br><br>
                <?php if ($this->error): ?>
                    <h4 class="text-danger"><b><span class="fa fa-warning"></span> Usuário ou senha inválidos</b></h4>
                    <hr />
                <?php endif; ?>
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('busao-admin-auth'));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('email')) . "<br>";
                echo $this->formRow($form->get('password')) . "<br>" . "<br>";
                echo $this->formSubmit($form->get('submit')) . "<br>";
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>

