
<!-- Content Header (Page header) -->
<section class="content-header">
    <ol class="breadcrumb">
        <li>Você está em: <a href="/"> &nbsp;<i class="fa fa-bus"> </i>Home</a></li> <li class="active">Linhas Regulares</li>
    </ol>
    <h1>
        <small>Bairro</small>
        <span class="fa fa-map-marker"></span> ARACELI
    </h1>
</section>

<section class="content">

    <!-- HORARIOS/INTINERÁRIO -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header"><i class="fa fa-clock-o"></i> Horários</h2>

            <ul id="myTab" class="nav nav-tabs nav-justified">
                <li class="active"><a href="#service-one" data-toggle="tab"><h4><i class="fa fa-calendar"></i> DIAS ÚTEIS</h4></a>
                </li>
                <li class=""><a href="#service-two" data-toggle="tab"><h4><i class="fa fa-calendar"></i> SÁBADO</h4></a>
                </li>
                <li class=""><a href="#service-three" data-toggle="tab"><h4><i class="fa fa-calendar"></i> DOMINGOS</h4></a>
                </li>
                <li class=""><a href="#service-four" data-toggle="tab"><h4><i class="fa fa-road"></i> INTINERÁRIO</h4></a>
                </li>
            </ul>

            <div id="myTabContent" class="tab-content">

                <div class="tab-pane fade active in" id="service-one">
                    <!--========== Dias Úteis ============-->
                    <h3 align="center">DIAS ÚTEIS</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="success">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-right fa-2x"></i> Saída do <strong>CENTRO</strong></h4></div></th>
                                </tr>
                                </thead>

                                <tbody>
                                    <tr align="center"><td><h4>06:17</h4></td></tr>
                                    <tr align="center"><td><h4>06:44</h4></td></tr>
                                    <tr align="center"><td><h4>07:32</h4></td></tr>
                                    <tr align="center"><td><h4>08:32</h4></td></tr>
                                    <tr align="center"><td><h4>09:32</h4></td></tr>
                                    <tr align="center"><td><h4>10:52</h4></td></tr>
                                    <tr align="center"><td><h4>11:34</h4></td></tr>
                                    <tr align="center"><td><h4>12:14</h4></td></tr>
                                    <tr align="center"><td><h4>12:54</h4></td></tr>
                                    <tr align="center"><td><h4>13:40</h4></td></tr>
                                    <tr align="center"><td><h4>14:55</h4></td></tr>
                                    <tr align="center"><td><h4>16:10</h4></td></tr>
                                    <tr align="center"><td><h4>16:55</h4></td></tr>
                                    <tr align="center"><td><h4>17:35</h4></td></tr>
                                    <tr align="center"><td><h4>18:15</h4></td></tr>
                                    <tr align="center"><td><h4>19:00</h4></td></tr>
                                    <tr align="center"><td><h4>20:15</h4></td></tr>
                                    <tr align="center"><td><h4>21:25</h4></td></tr>
                                    <tr align="center"><td><h4>22:35</h4></td></tr>
                                </tbody>


                            </table>
                        </div>

                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="success">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-left fa-2x"></i> Saída do <strong>BAIRRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>05:48</h4></td></tr>
                                    <tr align="center"><td><h4>06:15</h4></td></tr>
                                    <tr align="center"><td><h4>06:51</h4></td></tr>
                                    <tr align="center"><td><h4>07:18</h4></td></tr>
                                    <tr align="center"><td><h4>08:06</h4></td></tr>
                                    <tr align="center"><td><h4>09:06</h4></td></tr>
                                    <tr align="center"><td><h4>10:06</h4></td></tr>
                                    <tr align="center"><td><h4>11:26</h4></td></tr>
                                    <tr align="center"><td><h4>12:10</h4></td></tr>
                                    <tr align="center"><td><h4>12:50</h4></td></tr>
                                    <tr align="center"><td><h4>13:30</h4></td></tr>
                                    <tr align="center"><td><h4>14:14</h4></td></tr>
                                    <tr align="center"><td><h4>15:29</h4></td></tr>
                                    <tr align="center"><td><h4>16:46</h4></td></tr>
                                    <tr align="center"><td><h4>17:31</h4></td></tr>
                                    <tr align="center"><td><h4>18:11</h4></td></tr>
                                    <tr align="center"><td><h4>19:34</h4></td></tr>
                                    <tr align="center"><td><h4>20:49</h4></td></tr>
                                    <tr align="center"><td><h4>21:59</h4></td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>   
                <!---FIM DA TABELA DO HORÁRIO DE SEGUNDA A SEXTA-->


                <!---TABELA DO HORÁRIO DE SÁBADO-->
                <div class="tab-pane fade" id="service-two">
                    <!--========== Sábados ============-->
                    <h3 align="center">SÁBADOS</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="active">
                                        <th>
                                <div align="center"><h4><i class="fa fa-arrow-circle-right fa-2x"></i> Saída do <strong>CENTRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>06:35</h4></td></tr>
                                    <tr align="center"><td><h4>07:45</h4></td></tr>
                                    <tr align="center"><td><h4>08:45</h4></td></tr>
                                    <tr align="center"><td><h4>10:05</h4></td></tr>
                                    <tr align="center"><td><h4>11:15</h4></td></tr>
                                    <tr align="center"><td><h4>12:15</h4></td></tr>
                                    <tr align="center"><td><h4>13:25</h4></td></tr>
                                    <tr align="center"><td><h4>14:39</h4></td></tr>
                                    <tr align="center"><td><h4>15:53</h4></td></tr>
                                    <tr align="center"><td><h4>17:03</h4></td></tr>
                                    <tr align="center"><td><h4>18:03</h4></td></tr>
                                    <tr align="center"><td><h4>19:13</h4></td></tr>
                                    <tr align="center"><td><h4>20:20</h4></td></tr>
                                    <tr align="center"><td><h4>22:00</h4></td></tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="active">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-left fa-2x"></i> Saída do <strong>BAIRRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>05:57</h4></td></tr>
                                    <tr align="center"><td><h4>06:57</h4></td></tr>
                                    <tr align="center"><td><h4>08:07</h4></td></tr>
                                    <tr align="center"><td><h4>09:07</h4></td></tr>
                                    <tr align="center"><td><h4>10:27</h4></td></tr>
                                    <tr align="center"><td><h4>11:37</h4></td></tr>
                                    <tr align="center"><td><h4>12:37</h4></td></tr>
                                    <tr align="center"><td><h4>13:47</h4></td></tr>
                                    <tr align="center"><td><h4>15:01</h4></td></tr>
                                    <tr align="center"><td><h4>16:15</h4></td></tr>
                                    <tr align="center"><td><h4>17:25</h4></td></tr>
                                    <tr align="center"><td><h4>18:25</h4></td></tr>
                                    <tr align="center"><td><h4>19:35</h4></td></tr>
                                    <tr align="center"><td><h4>20:42</h4></td></tr>
                                    <tr align="center"><td><h4>22:22</h4></td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>

                <!---Tabela dos DOMINGOS E FERIADOS-->
                <div class="tab-pane fade" id="service-three">
                    <h3 align="center">DOMINGOS e FERIADOS</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="danger">
                                        <th>
                                <div align="center"><h4><i class="fa fa-arrow-circle-right fa-2x"></i> Saída do <strong>CENTRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>07:17</h4></td></tr>
                                    <tr align="center"><td><h4>13:02</h4></td></tr>
                                    <tr align="center"><td><h4>14:17</h4></td></tr>
                                    <tr align="center"><td><h4>15:32</h4></td></tr>
                                    <tr align="center"><td><h4>17:35</h4></td></tr>
                                    <tr align="center"><td><h4>18:50</h4></td></tr>
                                    <tr align="center"><td><h4>20:20</h4></td></tr>
                                    <tr align="center"><td><h4>22:00</h4></td></tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="danger">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-left fa-2x"></i> Saída do <strong>BAIRRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>06:43</h4></td></tr>
                                    <tr align="center"><td><h4>07:36</h4></td></tr>
                                    <tr align="center"><td><h4>13:21</h4></td></tr>
                                    <tr align="center"><td><h4>14:36</h4></td></tr>
                                    <tr align="center"><td><h4>15:51</h4></td></tr>
                                    <tr align="center"><td><h4>17:54</h4></td></tr>
                                    <tr align="center"><td><h4>19:09</h4></td></tr>
                                    <tr align="center"><td><h4>20:39</h4></td></tr>
                                    <tr align="center"><td><h4>22:19</h4></td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>
                <!--========== FIM do dias da Semana ============-->

                <!--========== intinerário ============-->
                <div class="tab-pane fade" id="service-four">
                </div><!--========== Fim do mapa do intinerário ============-->
                <h1 align="center"><small>Percurso <i class="fa fa-map-marker"></i></small> 313 <small>ARACELI</small></h1>

                <div class="row">
                    <div class="col-lg-6">
                        <ol class="breadcrumb">
                            <div align="center">
                                <h3><small>Centro</small> <i class="fa fa-arrow-circle-right"></i> BAIRRO</h3>
                            </div>
                        </ol>    
                        <div align="center">
                            <div id="percursodescricao">
                                <strong>Terminal Centro</strong><br /> Av. Doutor Sílvio Botelho<br /> <strong>Centro Cívico</strong><br /> Av. Doutor Sílvio Botelho<br /> Rua Castelo Branco<br /> Av. Presidente Castelo Branco<br /> Rua Bento Brasil<br /> Av. Eldorado<br /> Rua Antônio Cabral<br /> Av. General Sampaio<br /> Av. das Guianas<br /> Av. Brasil (BR-174)<br /> Av. Capitão Clovis da Costa<br><br>
                                <iframe src="https://maps.google.com/maps/ms?msid=200258270808067952057.0004f343cfc6653c42191&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=2.801941,-60.695515&amp;spn=0.159797,0.264187&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="100%" height="350px"></iframe>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <ol class="breadcrumb">
                            <div align="center">
                                <h3><small>Bairro</small> <i class="fa fa-arrow-circle-right"></i> CENTRO</h3>
                            </div>
                        </ol>
                        <div align="center">
                            <div id="percursodescricao">
                                Av. Capitão Clovis da Costa<br /> Av. Brigadeiro<br /> Rua Antônio Silvino de Alexandre<br /> Av. Estrela dAlva<br /> Rua Estrelinha<br /> Rua Rio Ereu<br /> Rua Rio Apiaú<br /> Rua CJ 09<br /> Av. Olímpica<br /> Rua JT-03<br /> Rua Ônix<br /> Rua JT-02<br /> Rua JT-10<br /> Rua Topázio<br /> Rua Ametista<br /> Rua José Francisco<br /> Rua Raio Solar<br /> Rua CJ 05<br /> Av. Centenário<br /> Av. Brasil (BR-174)<br /> Av. das Guianas<br /> Av. General Sampaio<br /> Rua Antônio Cabral<br /> Av. Eldorado<br /> Rua Bento Brasil<br /> Av. Presidente Castelo Branco<br /> Rua Castelo Branco<br /> Av. Doutor Sílvio Botelho<br /> <strong>Terminal Centro</strong><br><br>
                                <iframe src="https://maps.google.com/maps/ms?msid=200258270808067952057.0004f343e0f3b8cd841d7&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=2.798341,-60.700836&amp;spn=0.159798,0.264187&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="100%" height="350"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- /.content -->