
<!-- Content Header (Page header) -->
<section class="content-header">
    <ol class="breadcrumb">
        <li>Você está em: <a href="/"> &nbsp;<i class="fa fa-bus"> </i>Home</a></li> <li class="active">Linhas Regulares</li>
    </ol>
    <h1>
        <small>Av Ataide</small> TEIVE <span class="fa fa-map-marker"></span>
    </h1>
</section>

<section class="content">

    <!-- HORARIOS/INTINERÁRIO -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header"><i class="fa fa-clock-o"></i> Horários</h2>

            <ul id="myTab" class="nav nav-tabs nav-justified">
                <li class="active"><a href="#service-one" data-toggle="tab"><h4><i class="fa fa-calendar"></i> DIAS ÚTEIS</h4></a>
                </li>
                <li class=""><a href="#service-two" data-toggle="tab"><h4><i class="fa fa-calendar"></i> SÁBADO</h4></a>
                </li>
                <li class=""><a href="#service-three" data-toggle="tab"><h4><i class="fa fa-calendar"></i> DOMINGOS</h4></a>
                </li>
                <li class=""><a href="#service-four" data-toggle="tab"><h4><i class="fa fa-road"></i> INTINERÁRIO</h4></a>
                </li>
            </ul>

            <div id="myTabContent" class="tab-content">

                <div class="tab-pane fade active in" id="service-one">
                    <!--========== Dias Úteis ============-->
                    <h3 align="center">DIAS ÚTEIS</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="success">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-right fa-2x"></i> Saída do <strong>CENTRO</strong></h4></div></th>
                                </tr>
                                </thead>

                                <tbody>
                                    <tr align="center"><td><h4>06:58</h4></td></tr>
                                    <tr align="center"><td><h4>07:05</h4></td></tr>
                                    <tr align="center"><td><h4>07:31</h4></td></tr>
                                    <tr align="center"><td><h4>11:25</h4></td></tr>
                                    <tr align="center"><td><h4>11:43</h4></td></tr>
                                    <tr align="center"><td><h4>12:05</h4></td></tr>
                                    <tr align="center"><td><h4>12:39</h4></td></tr>
                                    <tr align="center"><td><h4>13:39</h4></td></tr>
                                    <tr align="center"><td><h4>17:40</h4></td></tr>
                                    <tr align="center"><td><h4>18:06</h4></td></tr>
                                    <tr align="center"><td><h4>18:32</h4></td></tr>
                                </tbody>

                            </table>
                        </div>

                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="success">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-left fa-2x"></i> Saída do <strong>BAIRRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>06:36</h4></td></tr>
                                    <tr align="center"><td><h4>07:02</h4></td></tr>
                                    <tr align="center"><td><h4>07:28</h4></td></tr>
                                    <tr align="center"><td><h4>12:13</h4></td></tr>
                                    <tr align="center"><td><h4>12:38</h4></td></tr>
                                    <tr align="center"><td><h4>13:06</h4></td></tr>
                                    <tr align="center"><td><h4>18:06</h4></td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>   
                <!---FIM DA TABELA DO HORÁRIO DE SEGUNDA A SEXTA-->


                <!---TABELA DO HORÁRIO DE SÁBADO-->
                <div class="tab-pane fade" id="service-two">
                    <!--========== Sábados ============-->
                    <h3 align="center">SÁBADOS</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="active">
                                        <th>
                                <div align="center"><h4><i class="fa fa-arrow-circle-right fa-2x"></i> Saída do <strong>CENTRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>N/A</h4></td></tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="active">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-left fa-2x"></i> Saída do <strong>BAIRRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>N/A</h4></td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>

                <!---Tabela dos DOMINGOS E FERIADOS-->
                <div class="tab-pane fade" id="service-three">
                    <h3 align="center">DOMINGOS e FERIADOS</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="danger">
                                        <th>
                                <div align="center"><h4><i class="fa fa-arrow-circle-right fa-2x"></i> Saída do <strong>CENTRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>N/A</h4></td></tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-6">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="danger">
                                        <th><div align="center"><h4><i class="fa fa-arrow-circle-left fa-2x"></i> Saída do <strong>BAIRRO</strong></h4></div></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr align="center"><td><h4>N/A</h4></td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>
                <!--========== FIM do dias da Semana ============-->

                <!--========== intinerário ============-->
                <div class="tab-pane fade" id="service-four">
                </div><!--========== Fim do mapa do intinerário ============-->

                <h1 align="center"><small>Percurso <i class="fa fa-map-marker"></i></small> 313 <small>ARACELI</small></h1>

                <div class="row">
                    <div class="col-lg-6">
                        <ol class="breadcrumb">
                            <div align="center">
                                <h3><small>Centro</small> <i class="fa fa-arrow-circle-right"></i> BAIRRO</h3>
                            </div>
                        </ol>    
                        <div align="center">
                            <h4>Av. Ataíde Teive<br /> Av. Terêncio Lima<br /> Av. Glaycon de Paiva<br /> <strong>Centro Cívico</strong><br /> Av. Doutor Sílvio Botelho<br /> <strong>Terminal Centro</strong></h4><br>
                            <iframe src="https://maps.google.com/maps/ms?msid=200258270808067952057.0004f343c97ea4b2405f6&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=2.816686,-60.69912&amp;spn=0.159795,0.264187&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="100%" height="350"></iframe>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <ol class="breadcrumb">
                            <div align="center">
                                <h3><small>Bairro</small> <i class="fa fa-arrow-circle-right"></i> CENTRO</h3>
                            </div>
                        </ol>
                        <div align="center">
                            <h4><strong>Terminal Centro</strong><br /> Av. Doutor Sílvio Botelho<br /> <strong>Centro Cívico</strong><br /> Av. Mário Homem de Melo<br /> Av. São Sebastião<br /> Av. Ataíde Teive</h4><br>
                            <iframe src="https://maps.google.com/maps/ms?msid=200258270808067952057.0004f343c2fdddc318ed7&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=2.818915,-60.698948&amp;spn=0.159795,0.264187&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="100%" height="350"></iframe><small><br /></small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- /.content -->