<div class="wrapper row-offcanvas row-offcanvas-left">
    <!-- Left side column. contains the logo and sidebar -->
    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class="right-side">

        <!-- Main content -->
        <section class="content">


            <div class="row">
                <div class="col-lg-3">
                    <img class="img-responsive center-block" src="//www.google.com/images/errors/robot.png" alt="erro"/>
                </div>
                <div class="col-lg-9">

                    <h1>Ocorreu um erro!</h1>
                    <h2><?php echo $this->message ?></h2>

                    <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

                        <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
                            <hr/>
                            <h2>Additional information:</h2>
                            <h3><?php echo get_class($this->exception); ?></h3>
                        </div>
                    </div>
                    <dl>
                        <dt>File:</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                        </dd>
                        <dt>'Message':</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getMessage()) ?></pre>
                        </dd>
                        <dt>'Stack trace':</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                        </dd>
                    </dl>
                    <?php
                    $e = $this->exception->getPrevious();
                    if ($e) :
                        ?>
                        <hr/>
                        <h2>'Previous exceptions':</h2>
                        <ul class="unstyled">
                            <?php while ($e) : ?>
                                <li>
                                    <h3><?php echo get_class($e); ?></h3>
                                    <dl>
                                        <dt>'File':</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                                        </dd>
                                        <dt>'Message':</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getMessage()) ?></pre>
                                        </dd>
                                        <dt>'Stack trace':</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getTraceAsString()) ?></pre>
                                        </dd>
                                    </dl>
                                </li>
                                <?php
                                $e = $e->getPrevious();
                            endwhile;
                            ?>
                        </ul>
                    <?php endif; ?>

                <?php else: ?>

                    <h3>'No Exception available'</h3>

                <?php endif ?>

            <?php endif
            ?>

        </section>
    </aside>
</div><!-- ./wrapper -->


<!-- jQuery 2.0.2 -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../../js/bootstrap.min.js" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="../../js/AdminLTE/app.js" type="text/javascript"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../js/AdminLTE/demo.js" type="text/javascript"></script>