
<!-- Content Header (Page header) -->
<section class="content-header">
    <ol class="breadcrumb">
        <li>Você está em: <a href="/"> &nbsp;<i class="fa fa-line-chart"> </i>Linhas</a></li> <li class="active">Percusro</li>
    </ol>
    <h1>
        <span class="fa fa-map-marker"></span> Rotas
        <!--<small> Regulares</small>-->
    </h1>
</section>
<section class="content">
    <h2><span class="fa fa-line-chart"></span> Rotas</h2>
    <a class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('livraria-admin', array('controller' => 'livros', 'action' => 'new')) ?>" role="button"><span class="fa fa-plus"></span> Nova Rota</a>
    <br />
    <br />
    <table class="table table-hover table-responsive">
        <tr class="active">
            <!--<th>#</th>-->
            <th>Linha</th>
            <th>Percurso</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
        <?php foreach ($this->data as $entity): ?>
            <tr>
                <td><?php echo $entity->getNome(); ?></td>
                <td><?php echo $entity->getCategoria(); ?></td>
                <td>
                    <a class="btn btn-success btn-xs" href="<?php echo $this->url('livraria-admin-interna', array('controller' => 'livros', 'action' => 'edit', 'id' => $entity->getId())); ?>"><span class="fa fa-pencil"></span> Editar</a>
                </td>
                <td>
                    <a class="btn btn-danger btn-xs" href="<?php echo $this->url('livraria-admin-interna', array('controller' => 'livros', 'action' => 'delete', 'id' => $entity->getId())); ?>" 
                       onclick="if (confirm('***********************************************\n\n    Deseja realmente excluir esta Rota?\n\n***********************************************\n')) {
                                           document.location = this.href;
                                       }
                                       return false;" id="dialog">
                        <span class="fa fa-trash"></span> Deletar</a>
                </td> 
            </tr>        
        <?php endforeach; ?>
    </table>
    <br>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>
</section><!-- /.content -->

