<h3>Novo livro</h3>

<br />

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('livraria-admin',array('controller'=>'livros','action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('categoria'));
echo $this->formRow($form->get('autor'));
echo $this->formRow($form->get('valor'));
echo $this->formRow($form->get('isbn'))."<br />";

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>