<h3>Login</h3>

<br />

<?php if ($this->error): ?>
    <p><b>Usuário ou senha inválidos</b></p>
<?php endif; ?>


<?php
$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin-auth'));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password')) . "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>