
<!-- Content Header (Page header) -->
<section class="content-header">
    <ol class="breadcrumb">
        <li>Você está em: <a href="/"> &nbsp;<i class="fa fa-bus"> </i>Home</a></li> <li class="active">Linhas Regulares</li>
    </ol>
    <h1>
        <span class="fa fa-map-marker"></span> Linhas
        <!--<small> Regulares</small>-->
    </h1>
</section>

<section class="content">

    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <h2>Editando Linha</h2>
            <hr />
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('livraria-admin-interna', array('controller' => 'categorias', 'action' => 'edit')));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('nome')) . "<br>";
            ?>
            <div class="row">
                <div class="col-lg-6"> 
                    <?php
                    echo $this->formSubmit($form->get('submit'));
                    echo $this->form()->closeTag();
                    ?>
                </div>
                <div class="col-lg-6"> 
                    <?php
//                echo $this->formSubmit($form->get('cancel'));
//                echo $this->form()->closeTag();
                    ?>
                    <a class="btn btn-default btn-block" href="<?php echo $this->url('livraria-admin', array('controller' => 'categorias')) ?>"><span class="fa fa-remove"></span> Cancelar</a>
                </div>
            </div>
        </div>
    </div>

</section>