<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Busão BV-RR')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
                ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
                ->prependStylesheet($this->basePath() . '/css/morris/morris.css')
                ->prependStylesheet($this->basePath() . '/css/jvectormap/jquery-jvectormap-1.2.2.css')
                ->prependStylesheet($this->basePath() . '/css/datepicker/datepicker3.css')
                ->prependStylesheet($this->basePath() . '/css/daterangepicker/daterangepicker-bs3.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
//                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
//                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>


    </head>

    <!--<body>-->

    <body class="skin-blue">
        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <a href="/" class="logo">
                <span class="fa fa-bus"></span> Busão BV-RR 
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bus"></i> Linhas <b class="caret"></b>
                                <span class="label label-success"><i class="fa fa-map-marker"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header bg-yellow-gradient">Linhas Regulars</li>
                                <li><a href="<?php echo $this->url('busao-admin', array('controller' => 'araceli')) ?>"><i class="fa fa-bus"></i> 313 - ARACELI</a></li>
                                <li><a href="<?php echo $this->url('busao-admin', array('controller' => 'ataide-teive')) ?>"><i class="fa fa-bus"></i> 310 - ATAIDE TEIVE</a></li>
                                <li><a href="bairros/bairro-dos-estados.php"><i class="fa fa-bus"></i> 252 - BAIRRO DOS ESTADOS</a></li>
                                <li><a href="bairros/bairro-uniao.php"><i class="fa fa-bus"></i> 104 - BAIRRO UNIÃO</a></li>
                                <li><a href="bairros/base-aerea.php"><i class="fa fa-bus"></i> 113 - BASE AÉREA</a></li>
                                <li><a href="bairros/cacari.php"><i class="fa fa-bus"></i> 112 - CAÇARI</a></li>
                                <li><a href="bairros/carana-ufrr.php"><i class="fa fa-bus"></i> 206 - CARANÃ-UFRR</a></li>
                                <li><a href="bairros/cauame-direto.php"><i class="fa fa-bus"></i> 308 - CAUAMÉ-DIRETO</a></li>
                                <li><a href="bairros/centenario.php"><i class="fa fa-bus"></i> 402 - CENTENÁRIO</a></li>
                                <li><a href="bairros/conjunto-cruviana.php"><i class="fa fa-bus"></i> 401 - CONJUNTO CRUVIANA</a></li>
                                <li><a href="bairros/equatorial.php"><i class="fa fa-bus"></i> 112 - EQUATORIAL</a></li>
                                <li><a href="bairros/joquei-clube-sao-bento.php"><i class="fa fa-bus"></i> 211 - JOQUEI CLUBE / SÃO BENTO</a></li>
                                <li><a href="bairros/nova-cidade-direto.php"><i class="fa fa-bus"></i> 215 - NOVA CIDADE</a></li>
                                <li><a href="bairros/nova-cidade.php"><i class="fa fa-bus"></i> 305 - NOVA CIDADE - DIRETO</a></li>
                                <li><a href="bairros/s-bot-bacabeira.php"><i class="fa fa-bus"></i> 301 - S. BOT. BACABEIRA</a></li>
                                <li><a href="bairros/sen-helio-campos.php"><i class="fa fa-bus"></i> 252 - SEN. HÉLIO CAMPOS</a></li>
                                <li><a href="bairros/silvio-botelho.php"><i class="fa fa-bus"></i> 251 - SÍLVIO BOTELHO</a></li>

                                <li class="footer"><a href="#">See All Messages</a></li>
                            </ul>
                        </li>

                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span>Jane Doe <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header bg-light-blue">
                                    <img src="<?php echo $this->basePath('/img/user.jpg'); ?>" class="img-circle" alt="User Image" />
                                    <p>
                                        Jane Doe - Admin do Sistema
                                        <small>Menbro desde Nov. 2012</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <!--                                <li class="user-body">
                                                                    <div class="col-xs-4 text-center">
                                                                        <a href="#">Followers</a>
                                                                    </div>
                                                                    <div class="col-xs-4 text-center">
                                                                        <a href="#">Sales</a>
                                                                    </div>
                                                                    <div class="col-xs-4 text-center">
                                                                        <a href="#">Friends</a>
                                                                    </div>
                                                                </li>-->
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="<?php echo $this->url('busao-admin-interna', array('controller' => 'users')) ?>" class="btn btn-default btn-flat">Perfil</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="<?php echo $this->url('busao-admin-logout', array('controller' => 'logout')) ?>" class="btn btn-default btn-flat">Sair</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <div class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="<?php echo $this->basePath('/img/onibus-boa-vista.png'); ?>" alt="Busão" />
                        </div>
                        <div class="pull-left info">
                            <p>Ônibus Boa Vista</p>

                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <!-- search form -->
                    <!--                    <form action="#" method="get" class="sidebar-form">
                                            <div class="input-group">
                                                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                                                <span class="input-group-btn">
                                                    <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                                                </span>
                                            </div>
                                        </form>-->
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li class="active">
                            <a href="/">
                                <i class="fa fa-home"></i> <span>Home</span>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-bus"></i>
                                <span>Todas as Linhas</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $this->url('busao-admin', array('controller' => 'araceli')) ?>"><i class="fa fa-angle-double-right"></i>ARACELI</a></li>
                                <li><a href="bairros/ataide-teive.php"><i class="fa fa-angle-double-right"></i>ATAIDE TEIVE</a></li>
                                <li><a href="bairros/bairro-dos-estados.php"><i class="fa fa-angle-double-right"></i>BAIRRO DOS ESTADOS</a></li>
                                <li><a href="bairros/bairro-uniao.php"><i class="fa fa-angle-double-right"></i>BAIRRO UNIÃO</a></li>
                                <li><a href="bairros/base-aerea.php"><i class="fa fa-angle-double-right"></i>BASE AÉREA</a></li>
                                <li><a href="bairros/cacari.php"><i class="fa fa-angle-double-right"></i>CAÇARI</a></li>
                                <li><a href="bairros/carana-ufrr.php"><i class="fa fa-angle-double-right"></i>CARANÃ-UFRR</a></li>
                                <li><a href="bairros/cauame-direto.php"><i class="fa fa-angle-double-right"></i>CAUAMÉ-DIRETO</a></li>
                                <li><a href="bairros/centenario.php"><i class="fa fa-angle-double-right"></i>CENTENÁRIO</a></li>
                                <li><a href="bairros/conjunto-cruviana.php"><i class="fa fa-angle-double-right"></i>CONJUNTO CRUVIANA</a></li>
                                <li><a href="bairros/equatorial.php"><i class="fa fa-angle-double-right"></i>EQUATORIAL</a></li>
                                <li><a href="bairros/joquei-clube-sao-bento.php"><i class="fa fa-angle-double-right"></i>JOQUEI CLUBE / SÃO BENTO</a></li>
                                <li><a href="bairros/nova-cidade-direto.php"><i class="fa fa-angle-double-right"></i>NOVA CIDADE</a></li>
                                <li><a href="bairros/nova-cidade.php"><i class="fa fa-angle-double-right"></i>NOVA CIDADE - DIRETO</a></li>
                                <li><a href="bairros/s-bot-bacabeira.php"><i class="fa fa-angle-double-right"></i>S. BOT. BACABEIRA</a></li>
                                <li><a href="bairros/sen-helio-campos.php"><i class="fa fa-angle-double-right"></i>SEN. HÉLIO CAMPOS</a></li>
                                <li><a href="bairros/silvio-botelho.php"><i class="fa fa-angle-double-right"></i>SÍLVIO BOTELHO</a></li>
                            </ul>
                        </li>

                        <li>
                            <a href="<?php echo $this->url('busao-admin-interna', array('controller' => 'livros')) ?>">
                                <i class="fa fa-map-marker"></i> <span>Percurso</span> <small class="badge pull-right bg-orange">rotas</small>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('busao-admin-interna', array('controller' => 'categorias')) ?>">
                                <i class="fa fa-line-chart"></i> <span>Linhas</span> <small class="badge pull-right bg-green">linhas</small>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('busao-admin-interna', array('controller' => 'users')) ?>">
                                <i class="fa fa-user"></i> <span>Usuários</span> <small class="badge pull-right bg-blue">users</small>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('busao-admin-interna', array('controller' => 'auth')) ?>">
                                <i class="fa fa-lock"></i> <span>Entrar</span> <small class="badge pull-right bg-red">login</small>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-folder"></i> <span>Examples</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="#pages/examples/invoice.html"><i class="fa fa-angle-double-right"></i> Invoice</a></li>
                                <li><a href="#pages/examples/login.html"><i class="fa fa-angle-double-right"></i> Login</a></li>
                                <li><a href="#pages/examples/register.html"><i class="fa fa-angle-double-right"></i> Register</a></li>
                                <li><a href="#pages/examples/lockscreen.html"><i class="fa fa-angle-double-right"></i> Lockscreen</a></li>
                                <li><a href="#pages/examples/404.html"><i class="fa fa-angle-double-right"></i> 404 Error</a></li>
                                <li><a href="#pages/examples/500.html"><i class="fa fa-angle-double-right"></i> 500 Error</a></li>
                                <li><a href="#pages/examples/blank.html"><i class="fa fa-angle-double-right"></i> Blank Page</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <div class="right-side">
                <!-- Main content -->

                <?php echo $this->content; ?>

                <div class="content">
                    <br />
                    <hr />
                    <footer>
                        <p>&copy;2014 by Rogerio Regis.</p>
                    </footer>
                </div>
            </div><!-- /.right-side -->
        </div><!-- ./wrapper -->


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- jQuery UI 1.10.3 -->
        <script src="/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
        <!-- Bootstrap -->
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- Morris.js charts -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
        <script src="js/plugins/morris/morris.min.js" type="text/javascript"></script>
        <!-- Sparkline -->
        <script src="/js/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <!-- jvectormap -->
        <script src="/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
        <script src="/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
        <!-- jQuery Knob Chart -->
        <script src="/js/plugins/jqueryKnob/jquery.knob.js" type="text/javascript"></script>
        <!-- daterangepicker -->
        <script src="/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
        <!-- datepicker -->
        <script src="/js/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
        <!-- Bootstrap WYSIHTML5 -->
        <script src="/js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
        <!-- iCheck -->
        <script src="/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>

        <!-- AdminLTE App -->
        <script src="/js/AdminLTE/app.js" type="text/javascript"></script>

        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src="/js/AdminLTE/dashboard.js" type="text/javascript"></script>

        <!-- AdminLTE for demo purposes -->
        <script src="/js/AdminLTE/demo.js" type="text/javascript"></script>

        <script src="/js/firulas.js"></script>

        <?php echo $this->inlineScript() ?>

        <script type="text/javascript">
            $(function () {

                "use strict";

                //iCheck for checkbox and radio inputs
                $('input[type="checkbox"]').iCheck({
                    checkboxClass: 'icheckbox_minimal-blue',
                    radioClass: 'iradio_minimal-blue'
                });

                //When unchecking the checkbox
                $("#check-all").on('ifUnchecked', function (event) {
                    //Uncheck all checkboxes
                    $("input[type='checkbox']", ".table-mailbox").iCheck("uncheck");
                });
                //When checking the checkbox
                $("#check-all").on('ifChecked', function (event) {
                    //Check all checkboxes
                    $("input[type='checkbox']", ".table-mailbox").iCheck("check");
                });
                //Handle starring for glyphicon and font awesome
                $(".fa-star, .fa-star-o, .glyphicon-star, .glyphicon-star-empty").click(function (e) {
                    e.preventDefault();
                    //detect type
                    var glyph = $(this).hasClass("glyphicon");
                    var fa = $(this).hasClass("fa");

                    //Switch states
                    if (glyph) {
                        $(this).toggleClass("glyphicon-star");
                        $(this).toggleClass("glyphicon-star-empty");
                    }

                    if (fa) {
                        $(this).toggleClass("fa-star");
                        $(this).toggleClass("fa-star-o");
                    }
                });

                //Initialize WYSIHTML5 - text editor
                $("#email_message").wysihtml5();
            });
        </script>

    </body>
</html>
