<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . "/page/" . $page;
    else
        return preg_replace('/\d/', $page, $urlPattern);
};
?>

<nav>
    <div class="paginationControl">
        <div class="text-center">Itens <?php echo $this->firstItemNumber; ?> a <?php echo $this->lastItemNumber; ?> - <?php echo $this->current; ?> de <?php echo $this->pageCount; ?> páginas.</div>

        <ul class="pager">
            <?php if ($this->pageCount): ?>
                <!-- First page link -->
                <?php if (isset($this->first)): ?>
                    <li class="previous"><a href="<?php echo $formatUrl($this->first) ?>"><span class="fa fa-angle-double-left"></span> Primeiro</a></li>
                <?php else: ?>
                    <li class="previous disabled"><span class="disabled"><a href="#"><span class="fa fa-angle-double-left"></span> Primeiro</a></span></li>
                <?php endif; ?>

                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li><a href="<?php echo $formatUrl($this->previous) ?>"><span class="fa fa-angle-left"></span> Anterior</a></li>
                <?php else: ?>
                    <li><span class="disabled"><a href="#"><span class="fa fa-angle-left"></span> Anterior</a></span></li>
                <?php endif; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <li><a href="<?php echo $formatUrl($this->next); ?>">Próximo <span class="fa fa-angle-right"></span></a></li>
                <?php else: ?>
                    <li><span class="disabled"><a href="#">Próximo <span class="fa fa-angle-right"></span></a></span></li>
                <?php endif; ?>

                <!-- Last page link -->
                <?php if (isset($this->last)): ?>
                    <li class="next"><a href="<?php echo $formatUrl($this->last); ?>">Último <span class="fa fa-angle-double-right"></span></a></li>
                <?php else: ?>
                    <li class="next"><span class="disabled"><a href="#">Último <span class="fa fa-angle-double-right"></span></a></span></li>
                            <?php endif; ?>
                        <?php endif; ?>
        </ul>
    </div>
</nav>