<!-- Content Header (Page header) -->
<section class="content-header">
    <ol class="breadcrumb">
        <li>Você está em: <a href="/"> &nbsp;<i class="fa fa-bus"> </i>Home</a></li> <li class="active">Linhas Regulares</li>
    </ol>
    <h1>
        <span class="fa fa-map-marker"></span> Linhas
        <!--<small> Regulares</small>-->
    </h1>
</section>
<br />
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">

        <!-- TO DO List -->
        <div class="box box-primary">
            <div class="box-header">
                <i class="fa fa-map-marker"></i>
                <h3 class="box-title"> Linhas</h3>

            </div><!-- /.box-header -->
            <div class="box-body">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Linhas Regulares</h3>
                        <div class="pull-right">
                            <span class="clickable filter" data-toggle="dropdawn" title="Toggle table filter" data-container="body">
                            </span>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="input-group">
                            <input type="text" class="form-control" id="dev-table-filter" data-action="filter"
                                   data-filters="#dev-table" placeholder="Filtrar..."
                                   data-toggle="tooltip" data-placement="top"
                                   title="Limpe o campo para exibir todos novamente!"/>
                            <div class="input-group-btn">
                                <button class="btn btn-success"><i class="fa fa-filter"></i></button>
                            </div>
                        </div>
                    </div>

                    <table class="table table-mailbox">
                        <thead>
                            <tr class="active">
                                <th><i class="fa fa-bus"></i> LINHA</th>
                                <th>HORÁRIO / PERCURSO</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="unread">
                                <td><i class="fa fa-2x">313</i></td>
                                <td><a href="<?php echo $this->url('livraria-admin', array('controller' => 'araceli')) ?>">ARACELI</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x">310</i></td>
                                <td><a href="bairros/ataide-teive.php">ATAIDE TEIVE</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x">252</i></td>
                                <td><a href="bairros/bairro-dos-estados.php">BAIRRO DOS ESTÁDOS</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x">104</i></td>
                                <td><a href="bairros/bairro-uniao.php">BAIRRO UNIÃO</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 113</i></td>
                                <td><a href="bairros/base-aerea.php">BASE AÉREA</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 112</i></td>
                                <td><a href="bairros/cacari.php">CAÇARÍ</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 206</i></td>
                                <td><a href="bairros/carana-ufrr.php">CARANÃ UFRR</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 308</i></td>
                                <td><a href="bairros/cauame-direto.php">CAUAMÉ - DIRETO</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 402</i></td>
                                <td><a href="bairros/centenario.php">CENTENÁRIO</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 401</i></td>
                                <td><a href="bairros/conjunto-cruviana.php">CONJUNTO CRUVIANA</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 112</i></td>
                                <td><a href="bairros/equatorial.php">EQUATORIAL</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 211</i></td>
                                <td><a href="bairros/joquei-clube-sao-bento.php">JOQUEI CLUBE / SÃO BENTO</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 215</i></td>
                                <td><a href="bairros/nova-cidade.php">NOVA CIDADE</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 305</i></td>
                                <td><a href="bairros/nova-cidade-direto.php">NOVA CIDADE - DIRETO</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 301</i></td>
                                <td><a href="bairros/s-bot-bacabeira.php">S. BOT. BACABEIRA</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 252</i></td>
                                <td><a href="bairros/sen-helio-campos.php">SEN. HÉLIO CAMPOS</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-2x"> 251</i></td>
                                <td><a href="bairros/silvio-botelho.php">SÍLVIO BOTELHO</a></td>
                                <td align="center"><i class="fa fa-star-o"></i></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
                <div class="input-group">
                    <input class="form-control" placeholder="Type message..."/>
                    <div class="input-group-btn">
                        <button class="btn btn-success"><i class="fa fa-filter"></i></button>
                    </div>
                </div>
            </div>
        </div><!-- /.box -->
    </div>
</div>

<section class="content">

    <h2><span class="fa fa-map-marker"></span> Percursos</h2>
    <br />

    <table class="table table-hover table-responsive">
        <tr class="active">
            <th>#</th>
            <th>Linha</th>
            <th>Percurso</th>
        </tr>
        <?php foreach ($this->categorias as $categoria): ?>

            <tr><?php foreach ($categoria->getLivros() as $livro): ?>
                    <td><?php echo $categoria->getId(); ?></td>
                    <td><i class="fa fa-bus"> <?php echo $livro->getNome(); ?></i></td>
                    <td><?php echo $categoria; ?></td>
                <?php endforeach; ?>
            </tr>

        <?php endforeach; ?>
    </table>

</section><!-- /.content -->



