<!-- Content Header (Page header) -->
<div class="content-header">
    <ol class="breadcrumb">
        <li>Você está em: <a href="/"> &nbsp;<i class="fa fa-line-chart"> </i>Linhas</a></li> <li class="active">Rotas</li>
    </ol>
    <h1>
        <span class="fa fa-map-marker"></span> Linhas
        <!--<small> Regulares</small>-->
    </h1>
</div>

<div class="content">

    <a class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('busao-admin', array('controller' => 'categorias', 'action' => 'new')) ?>" role="button"><span class="fa fa-plus"></span> Nova Linha</a>
    <br />
    <br />
    <table class="table table-hover table-responsive">
        <tr class="active">
            <th>#</th>
            <th>Nome</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>

        <?php foreach ($this->data as $entity): ?>
            <tr>
                <td><?php echo $entity->getId(); ?></td>
                <td><?php echo $entity->getNome(); ?></td>
                <td>
                    <a class="btn btn-success btn-xs" href="<?php echo $this->url('busao-admin-interna', array('controller' => 'categorias', 'action' => 'edit', 'id' => $entity->getId())); ?>"><span class="fa fa-pencil"></span> Editar</a>
                </td>
                <td>
                    <a class="btn btn-danger btn-xs" href="<?php echo $this->url('busao-admin-interna', array('controller' => 'categorias', 'action' => 'delete', 'id' => $entity->getId())); ?>" 
                       onclick="if (confirm('***********************************************\n\n  Deseja realmente excluir esta Linha?\n\n***********************************************\n')) {
                                   document.location = this.href;
                               }
                               return false;" id="dialog">
                        <span class="fa fa-trash"></span> Deletar</a>
                </td> 
            </tr>        
        <?php endforeach; ?>
    </table>

    <br>

    <?php // echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>


</div><!-- /.content -->
