<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Main content -->
    <section class="content"> 
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4">
                <h2>Nova Linha</h2>
                <hr />
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('busao-admin', array('controller' => 'categorias', 'action' => 'new')));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id'));
                echo $this->formRow($form->get('nome')) . "<br>";
                ?>
                <div class="row">
                    <div class="col-lg-6"> 
                        <?php
                        echo $this->formSubmit($form->get('submit'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                    <div class="col-lg-6">
                        <a class="btn btn-default btn-block" href="<?php echo $this->url('busao-admin', array('controller' => 'categorias')) ?>"><span class="fa fa-remove"></span> Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>



<!-- jQuery 2.0.2 -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../js/bootstrap.min.js" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="../js/AdminLTE/app.js" type="text/javascript"></script>
<!-- AdminLTE for demo purposes -->
<script src="../js/AdminLTE/demo.js" type="text/javascript"></script>        
<!-- Bootstrap WYSIHTML5 -->
<script src="../jsplugins//bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
<!-- iCheck -->
<script src="../jsplugins//iCheck/icheck.min.js" type="text/javascript"></script>
<!-- Page script -->