<section class="content">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <h2>Novo Usuário</h2>
            <hr />
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('livraria-admin', array('controller' => 'users', 'action' => 'new')));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            ?>
            <span class="fa fa-user"></span> <?php echo $this->formRow($form->get('nome')) . "<br>"; ?>
            <span class="fa fa-envelope"></span> <?php echo $this->formRow($form->get('email')) . "<br>"; ?>
            <span class="fa fa-lock"></span> <?php echo $this->formRow($form->get('password')) . "<br>"; ?>

            <div class="row">
                <div class="col-lg-6"> 
                    <?php
                    echo $this->formSubmit($form->get('submit'));
                    echo $this->form()->closeTag();
                    ?>
                </div>
                <div class="col-lg-6"> 
                    <a class="btn btn-default btn-block" href="<?php echo $this->url('livraria-admin', array('controller' => 'users')) ?>"><span class="fa fa-remove"></span> Cancelar</a>
                </div>
            </div>
        </div>
    </div>
</section>