<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('School of Net - ZF2')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')
?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('livraria-home') ?>">Livraria Admin</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                    <?php if ($this->UserIdentity('LivrariaAdmin')): ?>
                                <li class="active"><a href="<?php echo $this->url('livraria-admin', array('controller' => 'categorias')) ?>">Categorias</a></li>
                                <li class="active"><a href="<?php echo $this->url('livraria-admin', array('controller' => 'livros')) ?>">Livros</a></li>
                                <li class="active"><a href="<?php echo $this->url('livraria-admin', array('controller' => 'users')) ?>">Users</a></li>
                                <li class="active"><a href="<?php echo $this->url('livraria-admin-logout') ?>">Logout</a></li>
                    <?php endif; ?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>School of Net</p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
