<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Main content -->
    <section class="content"> 
        <h2><span class="fa fa-map-marker"></span> Percuso</h2>
        <a class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('busao-admin', array('controller' => 'livros', 'action' => 'new')) ?>" role="button"><span class="fa fa-plus"></span> Novo Percurso</a>
        <br />
        <br />
        <table class="table table-hover table-responsive">
            <tr class="active">
                <th class="text-center">#</th>
                <th class="text-center">Linha</th>
                <th class="text-center">Rota</th>
<!--                <th>Autor</th>
                <th>Valor</th>-->
                <th class="text-center">Favorito</th>
                <th class="text-center">Editar</th>
                <th class="text-center">Excluir</th>
            </tr>

            <?php foreach ($this->data as $entity): ?>
            <tr class="text-center">
                    <td><?php echo $entity->getId(); ?></td>
                    <td><?php echo $entity->getNome(); ?></td>
                    <td><?php echo $entity->getCategoria(); ?></td>
<!--                    <td><?php // echo $entity->getAutor(); ?></td>
                    <td><?php // echo $entity->getValor(); ?></td>
                    <td><?php // echo $entity->getIsbn(); ?></td>-->
                    <td class="small-col text-orange"><span class="fa fa-star"></span></td>
                    <td>
                        <a class="btn btn-success btn-xs" href="<?php echo $this->url('busao-admin-interna', array('controller' => 'livros', 'action' => 'edit', 'id' => $entity->getId())); ?>"><span class="fa fa-pencil"></span> Editar</a>
                    </td>
                    <td>
                        <a class="btn btn-danger btn-xs" href="<?php echo $this->url('busao-admin-interna', array('controller' => 'livros', 'action' => 'delete', 'id' => $entity->getId())); ?>" 
                           onclick="if (confirm('***********************************************\n\n       Deseja realmente excluir esta Rota?\n\n***********************************************\n')) {
                                       document.location = this.href;
                                   }
                                   return false;" id="dialog">
                            <span class="fa fa-trash"></span> Deletar</a>
                    </td> 
                </tr>        
            <?php endforeach; ?>
        </table>
        <br>
        <?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>
    </section>
</aside>


<!-- jQuery 2.0.2 -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../js/bootstrap.min.js" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="../js/AdminLTE/app.js" type="text/javascript"></script>
<!-- AdminLTE for demo purposes -->
<script src="../js/AdminLTE/demo.js" type="text/javascript"></script>        
<!-- Bootstrap WYSIHTML5 -->
<script src="../jsplugins//bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
<!-- iCheck -->
<script src="../jsplugins//iCheck/icheck.min.js" type="text/javascript"></script>