<!--<div class="content">-->
<div class="row">
    <div class="col-lg-12">

        <h2 class="text-center">Editando Percurso</h2>
        <hr />
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('busao-admin-interna', array('controller' => 'livros', 'action' => 'new')));
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        ?>

        <div class="row">
            <div class="col-lg-4"> 
                <div class="well">
                    <div class="row">
                        <h4 class="text-center">DIAS ÚTEIS</h4>
                        <div class="col-lg-6"> 
                            <!--ARECELI Saída do CENTRO dias úteis-->
                            <span class="fa fa-arrow-circle-right fa-2x"></span> <?php echo $this->formRow($form->get('nome')) . "<br />"; ?>
                        </div>
                        <div class="col-lg-6">
                            <!--ARECELI Saída do BAIRRO dias úteis-->
                            <span class="fa fa-arrow-circle-left fa-2x"></span> <?php echo $this->formRow($form->get('autor')) . "<br />"; ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4"> 
                <div class="well">
                    <div class="row">
                        <h4 class="text-center">SÁBADOS</h4>
                        <div class="col-lg-6"> 
                            <!--ARECELI Saída do CENTRO sábado-->
                            <span class="fa fa-arrow-circle-up fa-2x"></span> <?php echo $this->formRow($form->get('saida_bairro_sabado')) . "<br />"; ?>
                        </div>
                        <div class="col-lg-6"> 
                            <!--ARECELI Saída do BAIRRO dias sábado-->
                            <span class="fa fa-arrow-circle-down fa-2x"></span> <?php echo $this->formRow($form->get('isbn')) . "<br />"; ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4"> 
                <div class="well">
                    <div class="row">
                        <h4 class="text-center">DOMIGOS e FERIADOS</h4>
                        <div class="col-lg-6"> 
                            <!--ARECELI Saída do CENTRO dias domingos-->
                            <?php echo $this->formRow($form->get('saida_bairro_sabado')) . "<br />"; ?>
                        </div>
                        <div class="col-lg-6"> 
                            <!--ARECELI Saída do BAIRRO dias domigos-->
                            <?php echo $this->formRow($form->get('isbn')) . "<br />"; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">

                <div class="col-lg-6">
                    <div class="well"> 
                        <h4 class="text-center">INTINERÁRIO</h4>
                        <!--Intinerário 313 ARACELI-->
                        <?php echo $this->formRow($form->get('saida_bairro_sabado')) . "<br />"; ?>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="well"> 

                        <!--mudar categoria para a entrada do frame no map da goolge-->
                        <h4 class="text-center">MAPA DA ROTA</h4>
                        <span class="fa fa-map-marker"></span> <?php echo $this->formRow($form->get('categoria')) . "<br />"; ?>

                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 col-lg-offset-3"> 
                        <?php
                        echo $this->formSubmit($form->get('submit'));
                        echo $this->form()->closeTag();
                        ?>
                        <!--</div>
                        <div class="col-sm-6"> -->
                        <a class="btn btn-default btn-block" href="<?php echo $this->url('busao-admin', array('controller' => 'livros')) ?>"><span class="fa fa-remove"></span> Cancelar</a>
                    </div>
                </div>

            </div>
        </div>


    </div>
</div>
<!--</div>-->

